### ISSUE TITLE
The slack-notifier gem is automatically installed

### ISSUE THREAD

**Issue by schlick** [jobready/patches#21]
On a recent upgrade, I noticed that the `slack-notifier` gem was automatically installed when I bundled. Since this is a public gem, users may be using hipchat instead of slack. There appears to be an inconsistency here where the `slack-notifier` gem is installed but not the `hipchat` gem. Either install both or none (or remove hipchat entirely).

**Comment by s01ipsist** [comment]
HipChat is dead and will be shutdown in early 2019. It should just be removed.

**Comment by schlick** [comment]
😢 goodbye hipchat
