### ISSUE TITLE
List pending patches is broken

### ISSUE THREAD

**Issue by jhuizy** [jobready/patches#31]
The task `rake patches:pending` is failing with a `NoMethodError`

```bash
$ bundle exec rake patches:pending
rake aborted!
NoMethodError: undefined method `each' for Patches::Pending:Class
/bundle/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:259:in `method_missing'
/bundle/gems/patches-3.5.0/lib/tasks/patches.rake:25:in `block (2 levels) in <top (required)>'
/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bin/bundle:30:in `block in <main>'
/usr/local/bin/bundle:22:in `<main>'
Tasks: TOP => patches:pending
(See full trace by running task with --trace)
```

Looks like this is caused by attempting to call `.each` on the `Patches::Pending` class rather than an instance of that class (https://github.com/jobready/patches/blob/develop/lib/tasks/patches.rake#L25)

**Comment by schlick** [comment]
@jhuizy Do you think we can setup the same push to rubygems as you did with [moodle-rb](https://github.com/jobready/moodle-rb/pull/25)? I don't know/can't see what the setup is with the RUBYGEMS_AUTH_TOKEN and whether it is available for use with this repo.

**Comment by s01ipsist** [comment]
`RUBYGEMS_AUTH_TOKEN` is an Organization Secret available to this repo too. That same action should just work

**Comment by jhuizy** [comment]
@schlick @s01ipsist sure I'll make a new PR with the file. Am I good to merge #32 after 1 approval?

**Comment by schlick** [comment]
> @schlick @s01ipsist sure I'll make a new PR with the file. Am I good to merge #32 after 1 approval?

Absolutely
